### ISSUE TITLE
Test 2 and 3 not working

### ISSUE THREAD

**Issue by MediciPrime** [michael-weinstein/dsNickFury3PlusOrchid#3]
I am creating a genome wide pgRNA knockdown screen and I really want to get Elevation scores for my gRNAs.  At the moment I am able to get the 1st test in 'Debugging dsNickFury (invoke using python 3)' working but I am running into problems for the next two tests.  I have installed conda w/in the dependencies folder, made sure to setup the 'dsNickFury' environment w/in the 'env' folder and I am running the tests while having that environment activated.  I have also done the same thing for the 'elevation' environment and lastly I made sure to correctly update the 'settings.py' and 'guideseq.py' files.  While running the second test I am running into the following error:

AttributeError: 'str' object has no attribute 'decode'

I could fix this error however doing so results in additional more complicated errors and I have a feeling that this initial error shouldn't be raised in the first place.  I really just want to get this awesome program working but I have been struggling for the past two days.  I have followed all the steps outlined in both the 'dsNickFury3PlusOrchid' and 'Microsoft/Elevation' repositories.  The only thing I actively deviated from was completing the ~8 hr long guideseq.py step, so I am not sure if these errors are originating from that.  

Could you please help me in anyway you can and also please let me know if I can provide any additional information, thank you.

**Comment by jjc2718** [comment]
Hi - could you include the logging/messaging that you see before the error (either as an attached text file or just pasted into a comment)?

I'm not able to reproduce this on my system, but we had another user with a similar problem recently so I'd like to check if the errors are the same.

**Comment by jjc2718** [comment]
One other thing: could you confirm that `python2_bin` in `settings.py` is pointing to a Python 2 binary? (To check the version you can just run something like `../dependencies/Anaconda2/bin/python -V`, modified to wherever your `python2_bin` is instead of the path I have)

**Comment by MediciPrime** [comment]
Thank you for your response!  I fixed the 'python2_bin' location so that it now points to the elevation environment's 'bin/python' location.  This resulted in me getting a bit farther in the second test however I have now run into the following errors.
[error.txt](https://github.com/michael-weinstein/dsNickFury3PlusOrchid/files/2119976/error.txt)
It seems like it may be complaining about guideseq but I made sure to point DSNF_DIRECTORY to '/projects/b1042/LinLab/dsNickFury/dsNickFury3PlusOrchid' in guideseq.py.  What do you think is happening?

**Comment by jjc2718** [comment]
That error seems to be due to missing the file generated by the `guideseq.py` step in the Elevation documentation. Unfortunately the file is quite large, otherwise I would just attach it.

Could you try running that step (or were you running into errors with that step when setting up the Elevation repo before)?

**Comment by MediciPrime** [comment]
I am currently running that step so hopefully by tomorrow morning I will have the required 'guideseq_unique_MM6_end0_lim999999999.hdf5' file.  I will let you know what happens or if I run into an error that I can't solve.  Thank you again for your continued help!

**Comment by MediciPrime** [comment]
I have successfully created the 'guideseq_unique_MM6_end0_lim999999999.hdf5' file and as a result got much farther during the second test.  However I ran into the following error when it was trying to see if the Elevation model provided the correct score.  
[error.txt](https://github.com/michael-weinstein/dsNickFury3PlusOrchid/files/2128477/error.txt)

**Comment by jjc2718** [comment]
FYI, I'm working on this - will update as soon as I'm able to reproduce the issue.

**Comment by MediciPrime** [comment]
Sounds good, I really appreciate it!  Please let me know if I can provide you with any additional information to help you reproduce the issue.

**Comment by lfearnley** [comment]
There seems to be a set of candidate guideRNAs that trigger issues in Elevation for me; I've noticed this is a particular problem in selection mode. 

As an example, the following command hangs indefinitely, because the individual search jobs created by the TargetSelection object never see pickled search results being moved into .shieldHQ<timestamp>/completed:

`python dsNickFury3.3.py -m selection -s 20_NGG -g hg38 --matchSiteCutoff 5000 --targetSequence AGGCGGTTGGGAGCTGGGCAGGAGTTGAGCCAAAAGAGCTTGCTTACTTGCTGGGAGGCAGGGCCGGGAGAGCCCGACTTCAGGACAACTTGGGCCTGCGGCGGTCGCCGGGAGGCCCAACCTTGGCGTGGAGGAGCCCACCGACCGGAGACCATTTGGGGCCTGGAGATGCCATAGGAGGGCAGGAGCTCATCCTGGAGAGGCCACCGTGAGGCCTGACCTGGGCCTGGGGAGCTTGGCTTGAGGAAGCTGTGGGCCGACCAAGGCCGCCAGGAGATGGGTAGGCACTGAGTCCAAAGAGGTTGTTGAGAGGCAGGAATCGGGCCTGGAGACCCAACCAGGAAGAAGAGCTGGGCCCGGAGAGGATGCCCGGAGGGTGCAAGTGGGTCTGGAGAGGCCGACTTGAGGAGGTTCTGGGCCCGGAGAGGCCGCCGGAAGGGAAAACTGGGCCTGGAAAGGCCGTTGTCAGGAATGAGCCCCATGGGCCTGAAGAGGCCACTG --cluster --skipAzimuth --outputToFile temp_output_rank_1.txt`

If I run individual bash scripts (generated in .shieldHQ<timestamp>/), I see the jobs fail out in the Elevation step; if I append --noElevation to the script they run through producing output. I don't believe that it's an install issue with Elevation as perhaps 75% of the guides I've evaluated have completed without issue.

I don't get an awful lot of error messages being generated, unfortunately, and the cluster that I'm running on has a number of design quirks that could be impacting this; however, Behram's example also fails for me.

**Comment by jjc2718** [comment]
@MediciPrime could you run the Elevation tests independently (if you haven't already), and attach the output if there is any? To do this, go to the directory you have Elevation installed in, and run `python -m pytest tests/` (where `python` is the Python 2 environment pointed to by `python2_bin` in dsNickFury `settings.py`).

Hopefully this will help to pinpoint if the problem is with your Elevation setup, or elsewhere.

**Comment by MediciPrime** [comment]
@jjc2718 I activated the 'Elevation' [environment](https://github.com/Microsoft/Elevation) and ran `python -m pytest tests/` within the `dsNickFury/dependencies/elevation/`directory.  However I encountered the following error: 
[elevation_test.txt](https://github.com/michael-weinstein/dsNickFury3PlusOrchid/files/2168145/elevation_test.txt)  
I assume that this means there is a problem with my Elevation setup. :(

**Comment by deer-1-arch** [comment]
> I have successfully created the 'guideseq_unique_MM6_end0_lim999999999.hdf5' file and as a result got much farther during the second test. However I ran into the following error when it was trying to see if the Elevation model provided the correct score. [error.txt](https://github.com/michael-weinstein/dsNickFury3PlusOrchid/files/2128477/error.txt)

Hello! I have the same error,Could you please take a look?[

[error.txt](https://github.com/user-attachments/files/24998478/error.txt)

](url)
